steps:
  # Step 1: Install dependencies
  - name: "node:20"
    dir: "frontend"
    entrypoint: "npm"
    args: ["install"]

  # Step 2: Build React App
  - name: "node:20"
    dir: "frontend"
    entrypoint: "npm"
    args: ["run", "build"]

  # Step 3: Deploy to App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    dir: "frontend"
    args: ["gcloud", "app", "deploy", "--quiet"]

timeout: "1600s"

options:
  logging: CLOUD_LOGGING_ONLY
